version: '3.9'

services:
  db:
    image: postgres:16
    container_name: jurisdex-db
    environment:
      - POSTGRES_DB=${DB_NAME}         
      - POSTGRES_USER=${DB_USER}       
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    networks:
      - sql-com

  backend:
    build: ./backend
    container_name: jurisdex-backend
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DB_HOST=db        
      - DB_PORT=5432                  
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - sql-com
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: jurisdex-front
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3001:3001"
    networks:
      - sql-com
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  sql-com:
    driver: bridge
